[package]
name = "dbflux_driver_postgres"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
dbflux_core = { path = "../dbflux_core" }
dirs = "6"
log = "0.4"
postgres = "0.19"
native-tls = "0.2"
postgres-native-tls = "0.5"
ssh2 = "0.9"
uuid = { version = "1", features = ["v4"] }
