[workspace]
members = ["crates/dbflux"]
default-members = ["crates/dbflux"]
resolver = "2"

[workspace.dependencies]
dbflux = { path = "crates/dbflux" }
gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = "0.5.0"
smallvec = "1.13.2"
