[package]
name = "dbflux_ssh"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
dbflux_core = { path = "../dbflux_core" }
dirs = "6"
log = "0.4"
ssh2 = "0.9"
