[package]
name = "dbflux_driver_sqlite"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
dbflux_core = { path = "../dbflux_core" }
rusqlite = { version = "0.32", features = ["bundled"] }
